export const SHAPE_HANDLERS = {
  TOP_LEFT: "TOP_LEFT",
  TOP_RIGHT: "TOP_RIGHT",
  BOTTOM_LEFT: "BOTTOM_LEFT",
  BOTTOM_RIGHT: "BOTTOM_RIGHT",
  TOP: "TOP",
  LEFT: "LEFT",
  BOTTOM: "BOTTOM",
  RIGHT: "RIGHT",
  ROTATION: "ROTATION",
  ARROW_START: "ARROW_START",
  ARROW_END: "ARROW_END"
} as const;

export const HANDLER_SIZE = 8;
export const ROTATION_HANDLER_OFFSET = 25;